🌟 Exercise 1 : Array Creation and Manipulation

Instructions
Create a 1D NumPy array containing numbers from 0 to 9.

Expected Output:

In [1]:
import numpy as np

In [36]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

🌟 Exercise 2 : Type Conversion and Array Operations


Instructions
Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.



In [3]:
a =  [3.14, 2.17, 0, 1, 2]
b = np.array(a)
b

array([3.14, 2.17, 0.  , 1.  , 2.  ])

In [4]:
b = b.astype(int)
b

array([3, 2, 0, 1, 2])

🌟 Exercise 3 : Working with Multi-Dimensional Arrays
Instructions

Create a 3x3 NumPy array with values ranging from 1 to 9.


In [5]:
a = np.arange(1,10)
a = a.reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers
Instructions
Create a 2D NumPy array of shape (4, 5) filled with random numbers.

In [13]:
a = np.random.rand(4,5)
a = np.round(a, 2)
a

array([[0.89, 0.46, 0.06, 0.04, 0.47],
       [0.46, 0.93, 0.33, 0.97, 0.96],
       [0.79, 0.47, 0.7 , 0.14, 0.42],
       [0.77, 0.24, 0.25, 0.36, 0.35]])

🌟 Exercise 5 : Indexing Arrays
Instructions
Select the second row from a given 2D NumPy array.

In [23]:
a = np.arange(15,25)
a = a.reshape(2,5)
a[1]

array([20, 21, 22, 23, 24])

🌟 Exercise 6 : Reversing elements
Instructions
Reverse the order of elements in a given 1D NumPy array (first element becomes last).

In [24]:
a = np.arange(10)
a = a[::-1]
a

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

🌟 Exercise 7 : Identity Matrix
Instructions
Create a 4x4 identity matrix using NumPy.

In [27]:
b = np.eye(4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

🌟 Exercise 8 : Simple Aggregate Funcs
Instructions
Find the sum and average of a given 1D array.

In [32]:
x = 45
y = 4.5
z = int(45/4.5)
w = np.full(z, y)
w

array([4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5])

In [33]:
np.sum(w)

45.0

In [34]:
np.mean(w)

4.5

🌟 Exercise 9 : Create Array and Change its Structure
Instructions
Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

In [38]:
a = np.arange(1,21)
a = a.reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

🌟 Exercise 10 : Conditional Selection of Values
Instructions
Extract all odd numbers from a given NumPy array.

Expected Output:

In [40]:
a = np.arange(10)
a[a%2==1]

array([1, 3, 5, 7, 9])